language: ruby
rvm:
  - 2.1.4

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

script: 
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec